export const constants = {
  NODE_TYPES: {
    AGENT: 'agent',
    LLM: 'llm',
    INPUT: 'input',
    OUTPUT: 'output',
    DECISION: 'decision',
    ROUTER: 'router',
    CONDITIONAL: 'conditional',
    LOOP: 'loop',
    TRANSFORMER: 'transformer',
    VALIDATOR: 'validator',
    TEXT_PROCESSOR: 'text_processor',
    CUSTOM: 'custom',
    AGGREGATE: 'aggregate',
    MERGE: 'merge',
    COMBINE: 'combine',
  },
  NODE_COLORS: {
    agent: '#3b82f6',
    llm: '#8b5cf6',
    input: '#10b981',
    output: '#f59e0b',
    decision: '#ef4444',
    router: '#f97316',
    transformer: '#06b6d4',
    validator: '#84cc16',
    text_processor: '#14b8a6',
    custom: '#6b7280',
    aggregate: '#ec4899',
    merge: '#a855f7',
    combine: '#6366f1',
  },
  EXECUTION_STATUS_COLORS: {
    pending: '#6b7280',
    running: '#3b82f6',
    paused: '#f59e0b',
    completed: '#10b981',
    failed: '#ef4444',
    cancelled: '#6b7280',
  },
  WORKFLOW_TYPES: ['custom', 'data_pipeline', 'decision_tree', 'document', 'multi_agent', 'parallel'],
};
